spring:
  resources:
    static-locations: classpath:/resource/static/**, classpath:/frontend
  # 데이터 소스 설정
  datasource:
    username: root
    url: jdbc:mysql://jangbogo-mysql.c3lk9y2mo6do.ap-northeast-2.rds.amazonaws.com:3306/jangbogo?serverTimezone=UTC&characterEncoding=UTF-8
    password: 201803938!
  # JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # MVC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
  # Security OAuth
  security:
    oauth2.client:
      registration:
        naver:
          clientId: FMfoQEmCgy0qeWiIIjXC
          clientSecret : Cm_14BHZ0A
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://52.78.59.168:8080/login/oauth2/code/naver"
          scope:
            - name
            - email
          clientName: Naver

        kakao:
          clientId: 06efe4f3256d04119e741bd434865776
          clientSecret: aTh5EUCBudrCiVVFOAv3KLMdemJXNHyW
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://52.78.59.168:8080/login/oauth2/code/kakao"
          scope:
            - profile_nickname
            - account_email
          clientName: Kakao

        google:
          clientId: 311620989308-m7lf8sfc9p4mc9btior0tju996nltaol.apps.googleusercontent.com
          clientSecret: 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
          scope:
            - profile
            - email

      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response

        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
server:
  port: ${PORT:8080}
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

  access:
    expiration: 1800000 #  (1000L(ms -> s) * 60L(s -> m) * 30L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

logging:
  level:
    root: info
    backend: debug